include: package:flutter_lints/flutter.yaml
linter:
  rules:
    curly_braces_in_flow_control_structures: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    camel_case_types: false
    use_build_context_synchronously: false