name: Build APK
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.3.10
                  channel: stable
            - name: Build APK
              run: flutter create . && flutter build apk --release
            - name: Upload APK
              uses: actions/upload-artifact@v3
              with:
                  name: costaz-android.apk
                  path: build/app/outputs/apk/release/app-release.apk
